### ISSUE TITLE
Route Planner API Console

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#65] opened 2017-10-05 23:24 UTC
The current (prod) Route Planner API console in BCDC is experiencing formatting issues with the section headings. Specifically there are headings with inactive open/close icons. Please review and debug.

[API spec](https://github.com/bcgov/api-specs/blob/master/router/router.json):

[API console](https://catalogue.data.gov.bc.ca/dataset/bc-route-planner/resource/6da9690e-a5f5-4b5a-8833-eafc46a47256/view/6038df87-1d0c-4ced-bf7b-2b94b3e63a14):

[BCDC metadata record](https://catalogue.data.gov.bc.ca/dataset/bc-route-planner):

**Comment by banders** [comment] 2017-10-10 18:20
@BK01 @ll911 I think I have fixed the issues that you were referring to.  Pull request [here](https://github.com/bcgov/api-specs/pull/253).  

The current version of swagger-ui presents all tags listed in the top-level "tags" object.  Each is rendered as an expandable container listing all paths that have been assigned to the tag.  An expandable container that appears not to expand when clicked is caused by a top-level tag with no paths assigned.  To avoid this, I have removed the top-level tags that weren't used.

**Comment by BK01** [comment] 2017-10-11 17:09
@banders @ll911 Debugging issue in PROD. 

TypeError: NetworkError when attempting to fetch resource

**Comment by banders** [comment] 2017-10-11 17:47
@BK01 @ll911 I see a different error: _TypeError: Failed to fetch_

Looks like this error is because the HTTP OPTIONS request is failing.  For example:

curl -X OPTIONS "https://router.api.gov.bc.ca/directions.json?points=-123.70794%2C48.77869%2C-123.53785%2C48.38200&outputSRS=4326&criteria=shortest&distanceUnit=km&routeDescription=Routing%20results"

Could this be a Kong issue?

**Comment by ll911** [comment] 2017-10-11 18:14
https://router.api.gov.bc.ca/directions.json?routeDescription=spansProvinceFastest&points=-126.844567%2C49.978503%2C-122.799997%2C58.925305&outputSRS=4326&criteria=fastest&distanceUnit=km&apikey=${yourAPIKEY}<https://router.api.gov.bc.ca/directions.json?routeDescription=spansProvinceFastest&points=-126.844567%2C49.978503%2C-122.799997%2C58.925305&outputSRS=4326&criteria=fastest&distanceUnit=km&apikey=$%7byourAPIKEY%7d>

**Comment by ll911** [comment] 2017-10-11 18:21
https://online.swagger.io/validator/debug?url=https://raw.githubusercontent.com/bcgov/api-specs/master/router/router.json

**Comment by BK01** [comment] 2017-10-11 18:23
I found that a request to the API via web browser and script worked, however, I experienced the issue in the console. Getting the following message using the link provided by ll911 above.
"{"schemaValidationMessages":[{"level":"error","message":"Unable to read content.  It may be invalid JSON or YAML"}]}"

**Comment by banders** [comment] 2017-10-11 18:52
@BK01 @ll911 Fixed the parse error.  PR [here](https://github.com/bcgov/api-specs/pull/254).

... but I still see an error in the API Console when I try to execute a request.  I think swagger-ui might be omitting the api key from HTTP OPTIONS requests.

**Comment by BK01** [comment] 2017-10-16 21:08
I can see the same omission in the header.

**Comment by BK01** [comment] 2017-10-19 18:15
DataBC to explore options and examine gated geocoder vs. route planner with sending OPTIONS in request. New issue introduced with latest release of swagger.

**Comment by ll911** [comment] 2017-10-20 21:53
@BK01 this is fixed at GW

**Comment by BK01** [comment] 2017-10-20 22:00
UAT completed successfully in PROD

**Comment by BK01** [comment] 2017-11-17 16:33
UAT complete in cad.data. Headings verified.

**Closed as completed** 2017-11-21 23:02 UTC
Labels: bug
