### ISSUE TITLE
Swagger editor UI

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#60] opened 2017-09-15 21:49 UTC
Change the header colour and font of the swagger editor to match the following.

https://bcgov.github.io/mygovbc-bootstrap-theme/docs/index.html

**Comment by BK01** [comment] 2017-09-19 22:17
Need further support for OpenAPI 3 before upgrading the editor

**Comment by banders** [comment] 2017-11-14 23:33
This issue seems to be a duplicate of https://github.com/bcgov/DBC-APIM/issues/57.  We can probably close this one.

**Closed as completed** 2017-11-14 23:51 UTC
Labels: enhancement
